### ISSUE TITLE
apache cordova bootstrapping

### ISSUE THREAD

**Issue by dpinart** [aurelia/bootstrapper#11]
Hi
First ot all, I'm not sure this is the right place for this question.

I'd like to know how can I bootstrap an aurelia app in an apache cordova application. I've tried to add the scripts for jspm_packages/system.js and config.js in index.html and at deviceready event call System.import('aurelia-bootstrapper'); but no success, apache cordova splash with "Device is ready" text keeps on the screen and it doesn't seem aurelia app is starterd

**Comment by EisenbergEffect** [comment]
@cmichaelgraham You've done this right?

**Comment by cmichaelgraham** [comment]
[this solution](https://github.com/cmichaelgraham/aurelia-typescript/tree/typescript-1-5-port/skel-nav-esri-vs-ts-telerik) does it with telerik platform

**Comment by dpinart** [comment]
thanks for your response.

@cmichaelgraham this solution is using require as module loader, is there any restriction about using es6-module-loader ?

**Comment by cmichaelgraham** [comment]
i haven't worked through the es6-module-loader case, but see no reason why it won't work :+1: 

i'm guessing it is a matter of the sequence of events.  maybe staring up systemjs after the device ready?

is your code on a github repo or somewhere public?
