### ISSUE TITLE
Loading without System does not work

### ISSUE THREAD

**Issue by jods4** [aurelia/bootstrapper#13]
#9 was fixed quickly but not tested because the fix is not sufficient.

The problem is now that `aurelia-metadata` gets loaded first and it creates a very rudimentary `System` polyfill: basically just `forEachModule`.

When `aurelia-bootstrapper` loads, it sees `window.System` and tries to use it, which fails miserably.

The check that doesn't work: 
https://github.com/aurelia/bootstrapper/blob/master/src/index.js#L54

Why it fails:
https://github.com/aurelia/metadata/blob/master/src/metadata.js#L20

**Comment by EisenbergEffect** [comment]
I think we have this fixed now.

**Comment by jods4** [comment]
I tried with the latest `aurelia-metadata` but it did not work. The rest of the packages were still based on `aurelia-bootstrapper: ~0.13.1` though.

I have a project set up with requirejs, so let me know if you want me to test this.

**Comment by EisenbergEffect** [comment]
It's not released yet. Look for it later today or tomorrow morning. There will be a blog post to accompany the release.
