### ISSUE TITLE
css/bootstrap.css overrides styles/styles.css

### ISSUE THREAD

**Issue by J-F-Liu** [aurelia/bootstrapper#14]
The registered css/bootstrap.css file appear after styles/styles.css, how can I solve this issue?

**Comment by BBosman** [comment]
Import it the same way the `bootstrap.css` is included.

Instead of using a `link` tag in the html use an `import` statement in your js:
`import '../styles/styles.css!';`

And make sure this import is after the bootstrap css import.

**Comment by J-F-Liu** [comment]
The generated url with `import '../styles/styles.css!'` is http://localhost:9000/dist/styles/styles.css which is wrong.
If I use `import '/styles/styles.css!';` then get an error: Illegal module name "/styles/styles.css!""

**Comment by BBosman** [comment]
That's why I had the `..` in my example as the `styles` directory is at the same level as the `dist` directory, so you first need to go up a level to be able to reference the `styles` directory.
