### ISSUE TITLE
configure is called with undefined

### ISSUE THREAD

**Issue by bmcorser** [aurelia/bootstrapper#15]
when i try to do the most simple aurelia setup i can manage:

```
jspm init
jspm install aurelia-bootstrapper
```

then add `index.html`, with a `body` like this:

``` html
<body aurelia-app>
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      System.import('aurelia-bootstrapper');
    </script>
  </body>
```

i also have `app.js` with copy-pasta from the docs:

``` js
import {LogManager} from 'aurelia-framework';
import {ConsoleAppender} from 'aurelia-logging-console';

LogManager.addAppender(new ConsoleAppender());
LogManager.setLevel(LogManager.logLevel.debug);

export function configure(aurelia) {
  // the variable 'aurelia' is undefined here
  aurelia.use
    .defaultBindingLanguage()
    .defaultResources()
    .history()
    .router()
    .eventAggregator()
  aurelia.start().then(a => a.setRoot('app', document.body));
}
```

the `app.html` is just a pair of `template` tags

however, the thing crashes with `TypeError: Cannot read property 'use' of undefined`, which is annotated above. for some reason the `configure` function in `app.js` is being called with `undefined` ... !?

**Comment by gregoryagu** [comment]
try renaming app.js to main.js.  The bootstrapper is looking for main.js, not app.js.

**Comment by bmcorser** [comment]
```
GET http://localhost:8001/app.js 404 (File not found)
es6.promise.js:139 Unhandled promise rejection Error loading "app" at http://localhost:8001/app.js
File not found: http://localhost:8001/app.js
```

I don't think that's the case.

**Comment by gregoryagu** [comment]
Trust me, I tried it and it works :)  Once you have main.js in place, then you need app.js which usually has the router, and app.html with "Hello World" 

Then fire up and it should run.  If it doesn't, I will put a sample on GitHub, but I am going out for the evening at the moment.

**Comment by bmcorser** [comment]
Ok, I missed that I need both. Perhaps it was the instruction to rename that threw me.

So the bootstrapper wants `main.js` where we do configuration of the Aurelia instance, which by default expects `app.js` as the "entry point"?

Have a nice evening :dancer:
