### ISSUE TITLE
Cannot install 0.19.0

### ISSUE THREAD

**Issue by tomalec** [aurelia/bootstrapper#23]
I try to install via `jspm install aurelia-bootstrapper` and by downloading and running `jspm install`, both ends with:

``` log
err  Error: EPERM: operation not permitted, rename 'C:\Users\tomalec\AppData\Local\.jspm\packages\github\aurelia\logging-console@0.9.0\dist\amd' -> 'C:\Users\tomalec\AppData\Local\.jspm\packages\github\aurelia\.tmp-logging-console@0.9.0'
         at Error (native)
```

**Comment by EisenbergEffect** [comment]
You have some permissions issues gonig on on your machine. Please ask about this in the gitter channel and someone can probably assist you if you aren't sure what to do.

**Comment by tomalec** [comment]
Thanks, deleting `C:\Users\tomalec\AppData\Local\.jspm` folder, and re-running `jspm install` helped.
