### ISSUE TITLE
TodoMVC implementation

### ISSUE THREAD

**Issue by smarts** [aurelia/bootstrapper#24]
You should add an implementation using Aurelia to http://todomvc.com/
(My apologies if this is not the appropriate repository for this issue, but I wasn't quite sure where it would go)

**Comment by mttmccb** [comment]
Looks like there is one on the way https://github.com/tastejs/todomvc/pull/1545

**Comment by mhoyer** [comment]
That's true @mttmccb. The original source repository (for the PR) can be found here: https://github.com/mhoyer/todomvc-aurelia

**Comment by smarts** [comment]
Cool. I subscribed to that PR's thread so I'll know when it gets merged or deleted and will close this accordingly.

**Comment by smarts** [comment]
Awesome, it's been merged! - http://todomvc.com/examples/aurelia/
