### ISSUE TITLE
Electron no longer functions due to Issue #26 being fixed.

### ISSUE THREAD

**Issue by MiiCode2** [aurelia/bootstrapper#27]
The fix done in #26 has stopped Electron from launching any applications.

By reversing window.system and window.require checks in function createLoader(), Electron will start functioning again.

See the erroneous code here:
https://github.com/aurelia/bootstrapper/blob/faf80a96cc721b61313a83fca7967242dc2ed3f6/dist/commonjs/aurelia-bootstrapper.js#L54-L68

**Comment by EisenbergEffect** [comment]
It fixed another bug. So, we are going to have to rethink this because if we switch it back it will break other scenarios. I think core-js now defines system and confuses it if we switch. Need to think about it...

**Comment by EisenbergEffect** [comment]
Ok, this is fixed in master. We'll get it out in the next day or so.
