### ISSUE TITLE
Bootstrapping fails if main.js doesn't import anything

### ISSUE THREAD

**Issue by plwalters** [aurelia/bootstrapper#29]
Steps to reproduce - 
1. Clone skeleton
2. Install deps
3. Remove bootstrap import from `main.js`
4. Run application

The bootstrapper seems to get to I think to [this line](https://github.com/aurelia/bootstrapper/blob/master/src/index.js#L87) but `Aurelia` is undefined.  When adding bootstrap import back in for some reason it doesn't.

**Comment by egeland** [comment]
I suspect my isse (https://github.com/aurelia/skeleton-navigation/issues/266) may be related, given that the error I get is `TypeError: Aurelia is not a function`.

I'll see if I can use bootstrapper from `1.0.0-beta.1.0.2` and/or `master` and see if the problem goes away..

**Comment by egeland** [comment]
`1.0.0-beta.1.0.2` solves my problem!

**Comment by EisenbergEffect** [comment]
Yes. This was a bug that was fixed in the latest bootstrapper.
