### ISSUE TITLE
Default configuration's conditional for localhost is not working

### ISSUE THREAD

**Issue by gheoan** [aurelia/bootstrapper#33]
There are some issues with [this](https://github.com/aurelia/bootstrapper/blob/4ad9189330a6032cbd2fa07e2d90b762fc267b2b/src/index.js#L99) conditional.
Note that the conditional is inside a function that is called only if `aurelia-app` has no value (ex: beginner kits).
-  the condition is always `true` because `location.protocol` [includes the final "**:**"](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/protocol) (`http:` or `https:`)
- `location.protocol` isn't good for checking if running locally (ex: `localhost`) because for both Firefox and Chrome `location.protocol === 'http:' // true` on `localhost`

I suggest one of the following: 
- remove the conditional (keep the `developmentLogging()` call)
- use `location.port` instead of `location.protocol`. 

Will submit a PR with the change.
@EisenbergEffect

**Comment by EisenbergEffect** [comment]
Yes. PR appreciated.

**Comment by Gheoan** [comment]
@E I proposed 2 solutions. Which one do you prefer
