### ISSUE TITLE
Changes break focus.bind

### ISSUE THREAD

**Issue by afmuller** [aurelia/bootstrapper#37]
Hi

Some change in aurelia-bootstrapper between version 1.0.0-beta.1.1.1 and 1.0.0-beta.1.1.4 have caused "focus.bind" to stop working. 

I have a "focus.bind" on my form field to give focus to a field when the page loads. On version 1.0.0-beta.1.1.1 it worked perfectly. On version 1.0.0-beta.1.1.4 it does not. On 1.1.4, the event appears to fire before the page is displayed - causing the field to not get the focus.

I have reverted aurelia-bootstrapper back to 1.0.0-beta.1.1.1 (from 1.1.4) and it stated working again.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/templating-resources #199](https://github.com/aurelia/templating-resources/issues/199) via [**ZenHub.io**](https://www.zenhub.io/)
