### ISSUE TITLE
aurelia-bootstrapper@1.0.0-beta.1.1.4 is installing aurelia-polyfills@1.0.0-beta.1.0.5

### ISSUE THREAD

**Issue by shivajiraot** [aurelia/bootstrapper#39]
Not sure when this is changed, looks like in the last 2 days itself. When we try to jspm install a fresh copy of aurelia-bootstrapper@1.0.0-beta.1.1.4, it installs the dependency aurelia-polyfills@1.0.0-beta.1.0.5 instead of aurelia-polyfills@1.0.0-beta.1.0.1 that it used to. Somehow this breaks the app with error `Cannot read property 'Symbol(toStringTag)'`. Manually changing the version in config.js and re-installing fixed the issue. Please verify on your end, I am not 100% sure if this is the issue here.

**Comment by EisenbergEffect** [comment]
Fix for aurelia-polyfills is going out in release shortly.
