### ISSUE TITLE
Hard dependency on aurelia-polyfills

### ISSUE THREAD

**Issue by michaelmalonenz** [aurelia/bootstrapper#41]
Removing the hard dependency on core-js was undoubtedly a good thing, but now we are forced to include `aurelia-polyfills` in our bundle.

For those of us who have a well-established code base, sprinkled with lots of async - await functions, changing them is both time-consuming and non-trivial.

Now that we are down to tuning the deployment to squeeze every last drop of performance, I have discovered that even though we don't use `aurelia-polyfills` directly, we are forced to include the library in the bundle (the bootstrapper errors as below when it is excluded).  While this only increases the bundle size by 12KB, that's 12KB of dead weight.

![aurelia-polyfills](https://cloud.githubusercontent.com/assets/8335112/15059265/8d2bf3c4-1375-11e6-9296-5a2355bd61a5.png)

**Comment by EisenbergEffect** [comment]
In your config.js. map aurelia-polyfills to a different module with no implementation.
