### ISSUE TITLE
Add support for data-* attribute

### ISSUE THREAD

**Issue by joshlrogers** [aurelia/bootstrapper#43]
Per my understanding of the HTML5 recommendation we should be relying on data-\* attributes for custom element attributes.  Currently the bootstrapper only supports aurelia-app and not data-aurelia-app.  

I don't mind submitting a pull request for it but I wanted to make sure there wasn't a reason it isn't already supported before doing so.

**Comment by EisenbergEffect** [comment]
We would be interested in a a pr to add this but we cannot remove the existing attribute support. It's our understanding that data- isn't really that important anymore. We're happy to support it if you submit the pr though.
