### ISSUE TITLE
Please consider switching to Yarn for Javascript package management

### ISSUE THREAD

**Issue by lukehutch** [aurelia/bootstrapper#49]
**I'm submitting a feature request**

Please consider switching to Yarn over using raw npm, for Aurelia Bootstrapper and other js dep management for Aurelia.

See:

https://code.facebook.com/posts/1840075619545360
- **What is the motivation / use case for changing the behavior?**

Yarn has many advantages over using npm directly. In particular, dependencies are not duplicated, and Yarn is much faster than npm.

**Comment by MeirionHughes** [comment]
why can't you use yarn already?

**Comment by lukehutch** [comment]
I can. I'm suggesting switching to using it for the examples and in the bootstrapper.

**Comment by EisenbergEffect** [comment]
It seems a little premature to do all that.

**Comment by lukehutch** [comment]
Fair enough, closing.

**Comment by cornillemichiel** [comment]
One year down the line, would you still say it is premature? Can we potentially reopen this? Is Yarn the way to go now?

**Comment by EisenbergEffect** [comment]
It’s supported in the cli now :)

**Comment by Dhanielk** [comment]
@EisenbergEffect can we "unsupported" it? I am using NPM for dependencies and when I do, it will remove whole Aurelia project.
