### ISSUE TITLE
Using main.js without passing in a root should default to aurelia-app not body

### ISSUE THREAD

**Issue by plwalters** [aurelia/bootstrapper#5]
Currently if you specify the main value for aurelia-app like this -

`<div aurelia-app="main"></div>`
without specifying a target in the setRoot in main.js like this - 
`aurelia.start().then(a => a.setRoot());`

The bootstrapper bootstraps the app on the `body` instead of the div where `aurelia-app` was specified.  It should default back to the DOM element with the aurelia-app attribute instead of the body.

**Comment by EisenbergEffect** [comment]
Good catch!
