### ISSUE TITLE
Bootstrapper v2 attempts to use pal-nodejs while running on nwjs

### ISSUE THREAD

**Issue by timfish** [aurelia/bootstrapper#53]
I've just updated to bootstrapper to v2.0.0. My code runs in nwjs which is Chromium augmented with nodejs functionality. Now the application fails to run as the bootstrapper is trying to load `aurelia-pal-nodejs` rather than the standard browser `pal`

How is the pal detection working? nwjs exposes much of the node functionality so I'm guessing it thinks its running on node!

```
chrome-extension://dnfbalibhjknhcnpfialacgapijfkkil/dist/aurelia-pal-nodejs.js net::ERR_FILE_NOT_FOUND
```

**Comment by timfish** [comment]
And here is the offending line:

```
const isNodeLike = typeof process !== 'undefined' && !process.browser;
```

Replacing it with either of these would fix it:
```
const isNodeLike = typeof process !== 'undefined' && !process.browser && !process.versions['nw']
const isNodeLike = typeof process !== 'undefined' && !process.browser && !process.__nwjs
```

**Comment by EisenbergEffect** [comment]
@niieani Can you take a look at this?

**Comment by timfish** [comment]
`process.__nwjs` is actually undocumented so it might be better to rely on `process.versions['nw']`. Check out the docs:

http://docs.nwjs.io/en/latest/References/Changes%20to%20Node/

**Comment by EisenbergEffect** [comment]
@timfish Are you able to make a PR for the fix you've confirmed on your side? We can review and get out a quick release.

**Comment by timfish** [comment]
That fixes v2 my end

**Comment by timfish** [comment]
Many thanks for the swift response!

My app is still having issues after updating to v2.0.1 but they appear unrelated to nwjs as I get the same exception when loading in Chrome. I did notice it bumped the versions on a few other dependencies too. Reverting back and everything runs fine again.

Is there a clash with `reflect-metadata@0.1.8`?

**UPDATE**
I've opened another bug for that https://github.com/aurelia/templating-resources/issues/267

```
Uncaught (in promise) Error: Error invoking Show. Check the inner error for details.
------------------------------------------------
Inner Error Stack:
TypeError
    at Object.getOwnMetadata (http://localhost:8080/jspm_packages/npm/reflect-metadata@0.1.8/Reflect.js:387:19)
    at Object.getOwn (http://localhost:8080/jspm_packages/npm/aurelia-metadata@1.0.2/aurelia-metadata.js:52:22)
```

**Comment by EisenbergEffect** [comment]
Double check to make sure you've got all the latest Aurelia libs as well.
