### ISSUE TITLE
aurelia-pal-browser tryng loading in wwwroot folder with ASP.NET

### ISSUE THREAD

**Issue by mauriliofilho** [aurelia/bootstrapper#55]
**I'm submitting a bug report**
In my application trying to run, in the browser console it returns a 404 error for the aurelia-pal-browser files being loaded from the root folder of the localhost application: 1354 / aurelia-pal-browser. Js. 
 Placing the file in question in the root folder of the application it works perfectly, try to install from jspm from the command line, the same error occurs, the first attempt was made to install from a VS extension in which I use To install dependencies using any dependency manager, but even then the same problem still occurs.

* **Library Version:**
aurelia-pal-browser@1.1.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
6.9.2

* **NPM Version:**
3.10.9

* **JSPM Version**
JSPM 0.16.48

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

**Comment by Akelitz** [comment]
@mauriliofilho with commit 8ba596b the bootstrapper has been reworked "to detect and load the proper pal". As a result 'aurelia-pal-browser' is no longer among the required modules in the define declaration and SystemJS seems no longer able to load it properly. The package is still installed while installing 'aurelia-bootstrapper' but you need to manually map "aurelia-pal-browser" to "npm:aurelia-pal-browser@1.1.0" in the config.js file, right after the "aurelia-framework": "npm:aurelia-framework@1.0.8" mapping.

**Comment by CodingGorilla** [comment]
Is this to be a permanent requirement?  I tried to start on my first Aurelia app today, and was watching the PluralSight course 'Aurelia Fundamentals' and spent like 3 hours trying to figure out why my app wasn't working when I did exactly what the course told me to do, until I finally came across this issue.

**Comment by Akelitz** [comment]
@CodingGorilla to be honest I am not an expert of SystemJS, but I think the right procedure for brand new projects should be to install 'aurelia-pal-browser' by itself simply running 'jspm install aurelia-pal-browser' right after 'aurelia' and 'aurelia-bootstrapper'. I can't (because of my lack of knowledge) answer why 'aurelia-bootstrapper' still trigger the installation of 'aurelia-pal-browser' with a "wrong" reference.

**Comment by CodingGorilla** [comment]
@Akelitz I actually tried that, I found a stackoverflow post mentioning that you had to do a `jspm install npm:aurelia-pal-browser` (I think), but that didn't solve the problem.  I guess all I'm asking here is that if you need to do this there should probably be some documentation somewhere.

**Comment by openbooknoobdeveloper** [comment]
thanks for the help
