### ISSUE TITLE
Can't use es2015 or native-modules with webpack

### ISSUE THREAD

**Issue by jods4** [aurelia/bootstrapper#56]
Webpack throws an error when it sees a free variable `module` used in an ES module (i.e. in the same file as `import` or `export`).

`module` is found on lines 73 and 77 for NodeJS detection
https://github.com/aurelia/bootstrapper/blob/master/src/index.js#L73-L77

The consequence is that neither `es2015` nor `native-modules` are usable with Webpack currently.
This is important because es modules is a prerequisite for tree shaking.

Not sure yet what the best fix is.

**Comment by jods4** [comment]
@niieani beats me to it by 2 days, relevant issue: webpack/webpack#3917

**Comment by jods4** [comment]
Sorry for the quick posts: webpack published 2.2 rc5 today and this is fixed.

**Comment by TheLarkInn** [comment]
https://github.com/webpack/webpack/issues/3917#issuecomment-272712281 @niieani if you guys wanted to get your hands on it ahead of time (with this commit merged to master it may be our final RC *knocks on wood*), feel free and run against the commit temporarily.
