### ISSUE TITLE
ReferenceError: use before declaration in Edge

### ISSUE THREAD

**Issue by jods4** [aurelia/bootstrapper#59]
The ES2015 distribution of `aurelia-bootstrapper` triggers an error in Edge: "ReferenceError: use before declaration". And then the application doesn't start.

I did test before and never noticed that, so I wonder if it is an Edge regression in a recent update.
I have Edge 14.14393, I would be interested in other people testing this.

The offending code is line 126: 
```js
.then(({ Aurelia }) => startResolve(() => new Aurelia(loader)));
```
And `Aurelia` is the variable that Edge complains about.
The code above looks fine to me (given that `then` is called with an object that contains an `Aurelia` property).
It runs fine in Firefox and according to Kangax tables it should be supported in Edge as well.

Just changing the code as follows work.
```js
.then(({ Aurelia }) => { 
  return startResolve(() => new Aurelia(loader));
});
```
So I'd say this is more of an Edge bug, but since it impacts us it's good to know.

**Comment by jods4** [comment]
I have a minimal repro, it requires several conditions to trigger the bug, notably nested lambdas.
This breaks Edge 14.4393:
```js
function g(cb) { return g() }
let f = ({ x }) => g(() => x);
f({ x: 42 }); // should return 42 but throws "use before declaration".
```

**Comment by jods4** [comment]
Found a relevant Chakra bug: Microsoft/ChakraCore#2606.
It was opened 5 days ago, I guess it _is_ a recent update. :(

**Comment by niieani** [comment]
We don't need the lambda, we can use function notation if it's going to help, since we only use the scope anyway (no `this` calls). I'd say we can re-release with a workaround.
Good catch, by the way!

**Comment by jods4** [comment]
The bug is not hard to work around as it's very sensible to syntax. Even just adding braces (block) make it vanish.

If we publish a fix the hardest part is making sure minifiers don't simplify the syntax back to broken. For instance, if we add braces or `function` I would expect a minifier to remove them...

It was not a hard catch as unfortunately now Aurelia ES6 does not run at all in Edge. 😦

**Comment by jods4** [comment]
@EisenbergEffect do you want to publish a fix? I can PR one if you want to.

**Comment by EisenbergEffect** [comment]
Oh, definitely. If you send a PR I'll get it out today.

**Comment by jods4** [comment]
@EisenbergEffect The fix is in the linked PR, it works for me.

**Comment by EisenbergEffect** [comment]
Merged.

**Comment by EisenbergEffect** [comment]
Release coming in a few minutes.
