### ISSUE TITLE
Bootstrapper appears not to return promise

### ISSUE THREAD

**Issue by ordinaryorange** [aurelia/bootstrapper#65]
I've just spun up [this repo](https://github.com/ordinaryorange/aurelia-karma-test-bones) to get tests working with karma and jasmine.
However the `await component.create(bootstrap)` never returns, jasmine times out and the test fails.

I've done some debugging through the source code, and from what I can see it appears to be bootstrapper not completing a promise. When I say 'appears', I did get lost in all those promises, My c# brain much prefers async/await.
I've crossed compared to the skeleton, and cannot see any config's that I missing.
I'm 10 hours in and going crazy...what am I missing ?

**Comment by davismj** [comment]
The issue is that webpack is improperly configured and the AureliaPlugin is not being loaded. This causes aurelia-pal-browser loading to fail and bootstrapping to fail.

@EisenbergEffect this can be closed
