### ISSUE TITLE
isNodeLike returns incorrectly in browser

### ISSUE THREAD

**Issue by cliener** [aurelia/bootstrapper#71]
**I'm submitting a bug report**

* **Library Version:**
2.3.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.15.3

* **NPM Version:**
6.9.0

* **JSPM OR Webpack AND Version**
webpack 4.30.0

* **Browser:**
Chrome 73.0.3683.103 | Firefox 66.0.3 | Edge 44.17763.1.0
Effectively everything I have on hand

* **Language:**
all

**Current behavior:**
Throws error as below on load
`Unhandled rejection TypeError: Unable to get property 'node-webkit' of undefined or null reference`
This is triggered by the boolean `isNodeLike` being incorrectly set to true even though the code is being executed in the browser.

Inspecting the code in browser results in a bizarre situation where the console returns a different result from the dev tools as per this screenshot.
![Aurelia Bootstrapper 2019-05-03 142105](https://user-images.githubusercontent.com/1216996/57119721-af581300-6daf-11e9-9945-d794e09ab539.jpg)

This is the same section of code that caused issues in #53 

**Expected/desired behavior:**

* **What is the expected behavior?**
Variable `isNodeLike` should return false for browsers which can be achieved which testing for the explicit process properties being subsequently used i.e.
```
const isNodeLike = typeof process !== 'undefined' && typeof process.type !== 'undefined' && typeof process.versions !== 'undefined';
```

* **What is the motivation / use case for changing the behavior?**
Code fails to execute

**Comment by 3cp** [comment]
@cliener can you push up a demo repo for reproducing this error? It's very strange as there is no other user reporting this.

**Comment by gp-slick-coder** [comment]
Had the same issue. Did a Chrome browser update to Version 89.0.4389.90 (Official Build) (64-bit) and the error was gone.

**Comment by berkerdemirer** [comment]
We are having the same issue in 2024

**Comment by 3cp** [comment]
@berkerdemirer could you publish a demo repo?

**Comment by berkerdemirer** [comment]
It is quite hard to publish a demo repo because we are not sure what's the cause. We can't reproduce it reliably. Our repo where we are having the issue is quite old and in maintenance mode. I can just say that it just broke out of nowhere without any new commit

**Comment by 3cp** [comment]
@berkerdemirer try run `npm run analyze` in the project. It should bring up webpack analyze web ui. Try search "process" to see if it returns any module. Please share a screenshot if it found something.

<img width="684" alt="Screenshot 2024-04-18 at 7 48 53 AM" src="https://github.com/aurelia/bootstrapper/assets/1188806/a4594a47-e14d-44e9-a6da-b26ad48cf771">
