### ISSUE TITLE
A fresh `jspm install` of `aurelia/bootstrapper` results in a browser error in firefox and safari when the app is run

### ISSUE THREAD

**Issue by ifyio** [aurelia/bootstrapper#8]
A fresh `jspm install` of `aurelia/bootstrapper` results in a browser error in firefox and safari when the app is run. The error is as follows: 

```
Unhandled promise rejection Error loading "github:webcomponents/webcomponentsjs@0.6.2/HTMLImports.min" at http://localhost:9000/jspm_packages/github/webcomponents/webcomponentsjs@0.6.2/HTMLImports.min.js
Not Found: http://localhost:9000/jspm_packages/github/webcomponents/webcomponentsjs@0.6.2/HTMLImports.min.js
```

This is because `line 93` of `aurelia/bootstrapper@0.12.0/index.js` (https://github.com/aurelia/bootstrapper/blob/master/src/index.js#L93) is making a reference to the `webcomponentsjs/HTMLImports.min`, which is part of `webcomponentsjs@0.6.1`. However, `webcomponentsjs@0.6.2` is what currently ends up being installed for `aurelia/bootstrapper@0.12.0`  by default and `webcomponentsjs@0.6.2` does not contain a `HTMLImports.min.js` file, so it fails. Currently, the work around is to manually change the mapping in `config.js` so that it points to `webcomponentsjs@0.6.1` instead of `webcomponentsjs@0.6.2` (which is not ideal). The error is not seen in the skeleton navigation app because it is already set to `webcomponentsjs@0.6.1` in the `config.js` file when the skeleton app is installed with yoeman. If you remove the mappings from the `config.js` file, however, and then run `jspm install` again so that the mappings are rebuilt, then it is rebuilt with `webcomponentsjs@0.6.2` set as the dependency for `aurelia/loader@0.6.0`, though `aurelia/loader@0.6.0` has a hard dependency on `webcomponentsjs@0.6.1`. So I think either `aurelai/bootstrapper` has to be updated to work with `webcomponentsjs@0.6.2` or the dependency declared to be `webcomponentsjs": "github:webcomponents/webcomponentsjs@0.6.1` instead of `^0.6.1` in the `package.json` of `aurelia/loader` (https://github.com/aurelia/loader/blob/master/package.json#L31).

**Comment by EisenbergEffect** [comment]
This issue appears to have fixed itself. It looks like it was an incomplete release on the part of the webcomponents team. This 0.6.2 tag has been removed and the tags following it now have the correct files.
