### ISSUE TITLE
Loading aurelia-loader-default without System

### ISSUE THREAD

**Issue by jods4** [aurelia/bootstrapper#9]
The codebase from Aurelia makes extensive use of `System` api. At the same time, it's supposed to work without it, e.g. in a `requirejs` runtime. To that effect, `aurelia-loader-default` installs a very thin polyfill for `System` when it's missing (basically delegating to `require`).

The problem is that `aurelia-bootstrapper` loads `aurelia-loader-default` dynamically, with a call to `System.import`, which is of course impossible at that point.

It's a kind of chicken-and-egg problem. I don't know what was the thinking behind dynamically loading `aurelia-loader-default`. It seems to me the easiest fix is to import it statically.

I worked around this problem by making sure that `aurelia-loader-default` is loaded before `aurelia-bootstrapper` is, but that feels wrong. It feels like a magic incantation whereas it should be a basic dependency of the bootstrapper.

**Comment by EisenbergEffect** [comment]
Already fixed this and deployed the release. jspm update the bootstrapper and it should be fixed.

**Comment by npelletm** [comment]
cf https://github.com/aurelia/framework/issues/110 that fix it
too slow... ;-)

**Comment by jods4** [comment]
Fixed 6 hours before I reported it? That was fast! ;)
